name: Build Images

on:
  pull_request:
    branches: [ main, dev ]
    paths: [ 'src/unified/*.scad', 'src/small/*.scad']  
  push:
    branches: [ dev ]
    paths: [ 'src/unified/*.scad', 'src/small/*.scad']
  workflow_dispatch:
     inputs:
      workflow_02:
        description: 'Ù‹trigger upload of stls on shareStuff'
        required: true
        default: 'workflow_02'

      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'prasannax1'

      workflow2_repo_github:
        description: 'repo-name'
        required: true
        default: 'shareStuff'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        
    - name: Install dependencies
      run: |
        sudo apt install -y xvfb imagemagick openscad;
        
    - name: Start Xvfb
      run: |
        Xvfb :5 -screen 0 800x600x24 &
        export DISPLAY=:5
      
    - name: build images
      run: |
        export DISPLAY=:5
        cd images
        make
        cd -
               
    - name: build stls
      run: |
        export DISPLAY=:5
        cd stls/generated
        make -B
        cd -
        
    - name: commit changes and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add images/mother/* images/small/*
        git commit -m "images autogenerated by github"
        git add stls/generated/*
        git commit -m "stls autogenerated by github"
        git push      
        
    - name: trigger dispatch for shareStuff
      run: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/prasannax1/shareStuff/dispatches \
          -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'
