name: Build Images

on:
  push:
    branches: [ master ]
    paths: [ 'src/mother/*.scad', 'src/small/*.scad']
  pull_request:
    branches: [ master ]
    paths: [ 'src/mother/*.scad', 'src/small/*.scad']

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    
    - name: update
      run: |
        sudo apt update && sudo apt upgrade -y
        
    - name: Install dependencies
      run: |
        sudo apt install -y xvfb imagemagick openscad;
        
    - name: Start Xvfb
      run: |
        Xvfb :5 -screen 0 800x600x24 &
        export DISPLAY=:5
      
    - name: build images
      run: |
        export DISPLAY=:5
        cd images
        make
        cd -
               
    - name: build stls
      run: |
        export DISPLAY=:5
        cd stls/generated
        make -B
        cd -
        
    - name: commit changes and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add images/mother/* images/small/*
        git commit -m "images autogenerated by github"
        git add stls/generated/*
        git commit -m "stls autogenerated by github"
        git push      
        
