name: Build Images

on:
  push:
    branches: [ master ]
    paths: [ 'src/mother/*.scad', 'src/small/*.scad']
  pull_request:
    branches: [ master ]
    paths: [ 'src/mother/*.scad', 'src/small/*.scad']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    
    - name: Install dependencies
      run: |
        sudo apt install -y xvfb imagemagick openscad;
      
    - name: build images
      run: |
        Xvfb :5 -screen 0 800x600x24 &
        export DISPLAY=:5
        make
        
        
    - name: build stls
      run: |
        cd stls/generated
        Xvfb :5 -screen 0 800x600x24 &
        export DISPLAY=:5
        make
        cd -
        
    - name: commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add images/mother/* images/small/*
        git commit -m "images autogenerated by github"
        git add stls/generated/*
        git commit -m "stls autogenerated by github"
        git push      
        
